deployment:
  tasks:
    - echo "Activating Node.js environment..."
    - source /home/queurxla/nodevenv/api.queuemcwd.ph/24/bin/activate

    - export DEPLOY_PATH=/home/queurxla/api.queuemcwd.ph

    - echo "Installing dependencies..."
    - npm install --prefix $DEPLOY_PATH

    - echo "Building NestJS app..."
    - npm run build --prefix $DEPLOY_PATH

    - echo "Restarting Passenger app..."
    - touch $DEPLOY_PATH/tmp/restart.txt

    - echo "✅ Deployment completed successfully!"
