services:
    api:
        container_name: mcwd-api-prod
        image: ghcr.io/ctrlaltelite-devs/api.queuemcwd.ph:staging
        ports:
            - "5001:5001"
        env_file:
            - .env
        environment:
            - NODE_ENV=development
        networks:
            - mcwd-network-staging
networks:
    mcwd-network-staging:
        external: true
