services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: queuemcwd-api
        ports:
            - "5000:5000"
        env_file:
            - .env.test
