services:
    api:
        image: ghcr.io/ctrlaltelite-devs/api.queuemcwd.ph:latest
        ports:
            - "5000:5000"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        networks:
            - mcwd-network-prod
networks:
    mcwd-network-prod:
        external: true
