services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: queuemcwd-api
        ports:
            - "5000:5000"
        env_file:
            - .env.test
        depends_on:
            - redis
        networks:
            - mcwd-network

    redis:
        image: redis:7
        container_name: mcwd-redis
        ports:
            - "6379:6379"
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis_data:/data
        networks:
            - mcwd-network

volumes:
    redis_data:

networks:
    mcwd-network: {} # Compose-managed network
