services:
    api:
        image: ghcr.io/CtrlAltElite-Devs/mcwd-api:latest
        ports:
            - "5000:5000"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
